[package]
name = "contracts-streamflow-poller"
version = "0.1.0"
edition = "2021"


[dependencies]
solana-client = "1.9.5"
solana-program = "1.4.17"
serde = "1.0.127"
serde_json = "1.0.66"
borsh = "0.9.1"
solana-sdk = "1.9.5"
redis = { version = "0.17.0" }